### ISSUE TITLE
Add some documentation for quicktype-core library usage

### ISSUE THREAD

**Issue by ipamaas** [glideapps/quicktype#1293]
It would be great to find some documentaion for quicktype-core.

Maybe there is one but I could not find it?

This code based on a sample in quicktype-playground does not seem to work any longer?
```
quicktype({
          lang: "Java",
          sources: [
            {
              kind: "JSON",
              //name: /* this.state.topLevelName ||*/ "TopLevel",
              samples: ['{ "name": "David" }']
            }
          ],
          rendererOptions: { /*"just-types": true*/ }
        }).then(result => {
          this.editorTargetContent = result.lines.join("\n").trim();
        });
```

**Comment by runk** [comment]
👍 Having the same problem.

**Comment by runk** [comment]
Actually it's being followed up: https://github.com/quicktype/quicktype/issues/186 - from sounds of it we might have to do it ourselves.

**Comment by ipamaas** [comment]
There is also a blog post about how to use the quicktype library in case an output customization is needed:
http://blog.quicktype.io/customizing-quicktype/

However it would be great to just use the library with simple options as it was possible until v13.0.14.

Could not get the InputData sample running as it is described in the blog post.

**Comment by runk** [comment]
My problem with using all those undocumented internal library APIs is they might break w/o any notice

**Comment by dvdsgl** [comment]
Added to README
