### ISSUE TITLE
Enable quicktype extension to run on VS Code on the web

### ISSUE THREAD

**Issue by isidorn** [glideapps/quicktype#1834]
:wave: I'm Isidor, a PM from the VS Code team, and we recently announced VS Code for the Web at https://vscode.dev/, which provides a free, zero-install Microsoft Visual Studio Code experience running entirely in your browser.  You can learn more [here](https://code.visualstudio.com/docs/editor/vscode-web). 

We'd like to ensure quicktype can run in the web, and we have a guide for enabling extensions for the web [here](https://code.visualstudio.com/api/extension-guides/web-extensions). As a couple of highlights:

- In VS Code for the Web, both the UI and extension host run inside the browser.
- A web extension is structured like a regular extension, but with a different main file: it's defined by the `browser` property
- Access to workspace files needs to go through the VS Code file system API accessible at `vscode.workspace.fs`
- There are currently [three ways](https://code.visualstudio.com/api/extension-guides/web-extensions#test-your-web-extension) to test a web extension

Please let us know if you have questions or feedback on enabling your extension for the web - our team would love to learn from your experiences and collaborate. Thank you!

**Comment by bamurtaugh** [comment]
Hi @schani! I was wondering if you might have thoughts on this? We're happy to discuss if you have any questions or feedback. Thank you!

**Comment by schani** [comment]
@isidorn @bamurtaugh Apologies for the late reply, and thank you for the pointers!

I'm afraid we don't currently have the time to do this.  We do have an intern starting in two months at glideapps.com though - maybe he'll be up for doing this.

We also accept PRs ;-)
