### ISSUE TITLE
Package API Documentation

### ISSUE THREAD

**Issue by thegoldenmule** [glideapps/quicktype#186]
I'd love to use this, but I don't see any documentation on usage (hopefully I'm just missing it?). From what I can piece together from the `Live-reloading` section, you call quicktype like this:

`quicktype--lang csharp my-json.json`

This seems to work, but it was just a guess. Are there any parameters we can tweak? Other configuration like namespace or pocos?

**Comment by schani** [comment]
@thegoldenmule If you run `quicktype` without parameters, or with `--help`, do you not get a usage summary?

(Apart from that I do agree that we need to document the command line interface better)

**Comment by thegoldenmule** [comment]
I _do_ see that now. I apparently ran it correctly the first time. However, this is two parts:

1. It would certainly be handy to have that documentation visible on your GitHub.
2. How can I use this from `node`?

**Comment by dvdsgl** [comment]
The `README` is distributed with the `npm` package, and you can also view it here: https://www.npmjs.com/package/quicktype

We do need an automated way to:

1. Keep the `npm` README in sync with `quicktype --help`.
1. Make the documentation easier to discover from this repo.
1. Generate a `man` page.

@thegoldenmule I'm not sure what you mean by "use [quicktype] from `node`" –– the `quicktype` executable installed by `npm` is simply an executable JavaScript file that `node` executes.

**Comment by thegoldenmule** [comment]
Ah thanks! I'm not real familiar with the node ecosystem-- I didn't realize usage would be on npm and not on the website or github.

As for the "using from node" comment, I meant that it would be nice to be able to import and use quicktype in a node project (via require or import), not just use it from the CLI.

**Comment by dvdsgl** [comment]
Have you tried yet? It works exactly as you desribe.

```shell
$ npm install --save quicktype
```

Then `import` or `require` it as any other `npm` JavaScript module:

```js
import * as Main from "quicktype/Main";
```

**Comment by thegoldenmule** [comment]
Yes, I can do that, but I'm asking for documentation on how to use it once I import it. All I see are CLI docs.

**Comment by schani** [comment]
Sorry, we don't have that documentation yet.  There are two places where you can look, though.  The first one is the TypeScript type definition for `Main`:

    https://github.com/quicktype/quicktype/blob/master/cli/Main.d.ts

For an example on how to use it we can offer the CLI:

    https://github.com/quicktype/quicktype/blob/master/cli/quicktype.ts

If you have more specific questions, it's probably quicker if you [ask us on Slack](http://slack.quicktype.io/).  We'd also be super thankful for documentation contributions ;-)

**Comment by runk** [comment]
@schani @dvdsgl any updates on that? Link it broken because of all the ongoing effort put into the library.

Some examples would be great. I can perhaps hook into internals of the quicktype, but since there's nothing that's  acknowledged being "Programmatic interface", breaking change are going to happen. Wonder how it works in https://quicktype.io/, are you guys interpolating cli options, making temp files etc..?

**Comment by dvdsgl** [comment]
This is the main function exposed by the `npm` package: https://github.com/quicktype/quicktype/blob/master/src/quicktype-core/Run.ts#L629-L640

If you inspect the `Options` parameter type, and `SerializedRenderResult` return type, you should learn everything about the interface. Then someone needs to write up some examples and documentation--I'm sorry we don't have time to do this right now but would work with you on PRs.

**Comment by dvdsgl** [comment]
This is in the README now.
