### ISSUE TITLE
Consider adding a useful ToString()

### ISSUE THREAD

**Issue by thegoldenmule** [glideapps/quicktype#197]
For generated models, it would be useful to have a `ToString()` that prints out all the fields in a deterministic order. For example:

```csharp
public partial class Value
{
	[JsonProperty("A")]
	public string A { get; set; }

	[JsonProperty("B")]
	public string B { get; set; }

	[JsonProperty("C")]
	public string C { get; set; }

	override public string ToString()
	{
		return string.Format("[{0} A={1}, B={2}, C={3}]",
			GetType(),
			A,
			B,
			C);
	}
}
```

**Comment by dvdsgl** [comment]
It may be reasonable to implement`Equals`, `Hashcode`, and `ToString`... I'd certainly be fine to start with:

In the short term, I'd be fine with:

```csharp
	override public string ToString() => ToJson(this);
```

**Comment by thegoldenmule** [comment]
Hopefully without the arrow syntax but sure! ;)
