### ISSUE TITLE
Quicktype.io In Not Show Name And Source Top Bar

### ISSUE THREAD

**Issue by vinaytadhani11** [glideapps/quicktype#1987]
My Crome Not Show Name And SourceType : 

![Screenshot 2022-08-13 at 10 07 08 AM](https://user-images.githubusercontent.com/90753781/184468646-b1b6c51a-b4eb-4e44-8eda-1154756acb11.png)

My Google Crome In Search quicktype.io but in Class name not change :

This Top bar my Crome Not Show
![Screenshot 2022-08-13 at 10 08 19 AM](https://user-images.githubusercontent.com/90753781/184468704-6fdef2ff-f7a1-4a5a-a86a-ef2733849847.png)

**Comment by dvdsgl** [comment]
?
