### ISSUE TITLE
Go: generate struct with custom tag

### ISSUE THREAD

**Issue by dinilvsellerapp** [glideapps/quicktype#2204]
Currently on generating golang struct from json schema has default tags in this format 

```
type Seller struct {
	Fulfilment     *Fulfilment `json:"fulfilment,omitempty"`
	// firestore id            
	ID             string      `json:"ID"`
}
```

is there an option in Json-schema or quicktype generator to replace "json" with custom tag like "bson" or "firestore" as an additional support ?

Thanks

**Comment by dinilvsellerapp** [comment]
Any lead/help is much appreciated. 
Thanks in Advance.

**Comment by inferrinizzard** [comment]
This is possible as of #2286
