### ISSUE TITLE
Add `readonly` to TypeScript interfaces

### ISSUE THREAD

**Issue by NatoBoram** [glideapps/quicktype#2280]
A new option for making all properties `readonly` would be very useful in TypeScript

| Option | Result |
|--------|--------|
| ![Option](https://github.com/quicktype/quicktype/assets/10495562/e786e331-5dc1-417f-bc6c-ad0fa4dfba0b) | ![Result](https://github.com/quicktype/quicktype/assets/10495562/c0791c43-6377-40d0-ad1a-ee86a62bcb32) |

**Comment by inferrinizzard** [comment]
Resolved as of 23.0.158
