### ISSUE TITLE
DART : Add snake_case support for freezed

### ISSUE THREAD

**Issue by faizabdillah** [glideapps/quicktype#2339]
[Freezed ](https://pub.dev/packages/freezed)  will generate the json key based on the variable name, so if its not match the json key, we know whats gonna happen

![image](https://github.com/quicktype/quicktype/assets/36881303/28eb3754-cffe-49a8-b3fe-b3a7f39fd32a)

**Comment by kvnxiao** [comment]
This will be fixed by https://github.com/quicktype/quicktype/pull/2348

**Comment by inferrinizzard** [comment]
Resolved by #2348
