### ISSUE TITLE
VS Code Extension not updated since 2018-9-20, 17:48:28

### ISSUE THREAD

**Issue by SimonCahill** [glideapps/quicktype#2395]
Title pretty much says it all.

Are there any plans to update the VS Code extension?  
Community attempts have been made to provide updated versions of the extension, however due to the fact that Quicktype has >1.8m downloads, most people won't even consider other extensions.

```
Published          2017-12-23, 21:41:40
Last released     2018-9-20, 17:48:28
Identifier           quicktype.quicktype
```

**Comment by dvdsgl** [comment]
Would love for someone to contribute this!

**Comment by SimonCahill** [comment]
@dvdsgl Would that even be possible for someone outside of the core team?
AFAIK only you have access to the quicktype publisher account?

**Comment by raldebsi** [comment]
Last update is 28/09/2023 as of now

**Comment by dvdsgl** [comment]
We're now up to date with automated publishing to keep VS Code current.
