### ISSUE TITLE
How to ignore unwanted `"$schema"` property in the generated code?

### ISSUE THREAD

**Issue by mean-ui-thread** [glideapps/quicktype#2413]
My problem originated when I wanted to use a "$schema" in my JSON data, which gives Visual Studio Code users a better quality of life: Each fields could emit a pop-up describing what it is when `"description"` is present in the schema file, and also provides improved auto-completion, highlights errors including when required fields are missing, or if there is a typo, or using an enum value that isn't valid, or failing a string pattern or number ranges, etc etc
```json5
{
  "$schema": "./PersonSchema.json",
  "firstName": "Mean",
  "middleName: "UI",
  "lastName": "Thread",
  "age": 42
}
```
The problem is, I want to enforce my schema as strictly as possible, not allowing unknown properties, so I am setting `"additionalProperties"` to `false`. Unfortunately, the generated `Convert(json: string)` function will throw an exception because of the unknown "$schema" field found in my json data.

This forces me to add a `$schema` property in my `PersonSchema.json` :
```json5
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/Person",
  "definitions": {
    "Person": {
      "type": "object",
      "additionalProperties": false, // <--------------- IMPORTANT TO ME
      "properties": {
        "$schema": {  "type": "string" },  // <-------------------------- HERE
        "firstName": {  "type": "string" },
        "middleName": {  "type": "string" },
        "lastName": {  "type": "string" },
        "age": { "type": "number" }
      }
    }
  }
}
```
which ends up code-generating this property in typescript for example:
```typescript
export interface Person {
    schema?: string; // <--------------------------- HERE
    firstName?: string;
    middleName?: string;
    lastName?: string;
    age?: number;
}
```

Is there a way to skip `$schema` from being code-generated in the typescript interface without setting `"additionalProperties"` to `true`?

Ultimately, I would like this to fail:
```json5
{
  "$schema": "./PersonSchema.json",
  "firstName": "Mean",
  "middleName: "UI",
  "lastName": "Thread",
  "age": 42,
  "color": "blue"  // <----------------- this random data field that isn't part of the schema should not be allowed and should fail
}
```
And I would like my interface to look like this without any `"$schema"` properties:
```typescript
export interface Person {
    firstName?: string;
    middleName?: string;
    lastName?: string;
    age?: number;
}
```

Thanks!

**Comment by mean-ui-thread** [comment]
I'm wondering if ignoring every data fields in the json data file that starts with either `$` or `#` would be a viable way to solve this, as those fields are typically used for metadata (`$schema`, `$id`, `#ref`, etc), not an actual data field... :thinking:

**Comment by feefladder** [comment]
Note that language JSON and language JSON-schema `schema` are different. If you are using a JSON-schema, use `quicktype -s schema` aka `quicktype --src-lang schema`. This does not include the `$schema`

**Comment by mean-ui-thread** [comment]
@feefladder thank you for your reply. Unfortunately, I am using `--src-lang schema`, and I don't think you quite understand what I am saying. 

First of all, this works just fine:

`PersonSchema.json`:
```json5
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/Person",
  "definitions": {
    "Person": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "firstName": {  "type": "string" },
        "middleName": {  "type": "string" },
        "lastName": {  "type": "string" },
        "age": { "type": "number" }
      }
    }
  }
}
```
Which generates `Person.ts` just fine:
```typescript
export interface Person {
    firstName?: string;
    middleName?: string;
    lastName?: string;
    age?: number;
}
```
and can open this data json file just fine:
```json5
{
  "firstName": "Mean",
  "middleName: "UI",
  "lastName": "Thread",
  "age": 42
}
```
Everything works fine the way it should be.

Problem starts occuring when I wan't to add a schema line to the data json file:
```
```json5
{
  "$schema": "./PersonSchema.json", // <----------- NEED THIS LINE FOR VSCODE
  "firstName": "Mean",
  "middleName: "UI",
  "lastName": "Thread",
  "age": 42
}
```

And then I get this exception when I try to open it: `Invalid value for key "$schema" on Descriptor. Expected boolean but got "./PersonSchema.json"`

And the only way I solved this was to add `"$schema": {  "type": "string" },` to my schema file but it adds a `schema` property to my `Person.ts` and I don't want that.

I hope it makes sense...

**Comment by mean-ui-thread** [comment]
In case you're wondering why I want to add a schema line to the data json file, it is for visual studio code. Huge quality of life improvement when manually hand-writing these json data files:

![Screenshot from 2023-09-26 09-24-29](https://github.com/glideapps/quicktype/assets/961637/009762f4-40ec-4643-ab37-6c2d53151683)

**Comment by ceeeeej** [comment]
> In case you're wondering why I want to add a schema line to the data json file, it is for visual studio code. Huge quality of life improvement when manually hand-writing these json data files:
> 
> ![Screenshot from 2023-09-26 09-24-29](https://private-user-images.githubusercontent.com/961637/270670833-009762f4-40ec-4643-ab37-6c2d53151683.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3NTkzNTEsIm5iZiI6MTcwNDc1OTA1MSwicGF0aCI6Ii85NjE2MzcvMjcwNjcwODMzLTAwOTc2MmY0LTQwZWMtNDY0My1hYjM3LTZjMmQ1MzE1MTY4My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOVQwMDEwNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01OWRkZTBiNzI1Nzk1ZjdmMDU1YTk2YTZkZmY0ZTUwY2MxNzMzZjljYjBhMWNhMzY5MDk3ZWM1ZTVhNzQyNDhhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.v4HUgKq2uGURFdeucRX4iSRridos6KkFvgCsUeZ6gxY)

Maybe you can try something like this in your .vscode/settings.json file for the project:

```
{
    "json.schemas": [
        {
            "fileMatch": [
                "/*.json"
            ],
            "url": "myschema.jsonschema"
        }
    ]
}
```

**Comment by inferrinizzard** [comment]
This looks like too niche a use case, I would recommend the suggestion from @ceeeeej to configure your VSCode to provide the JSON Schema Intellisense without explicitly including the `$schema` property.

Or if you really wish to remove specific strings from your quicktype output, you can also do so but extending with a custom Renderer class
