### ISSUE TITLE
Document / add a setting for http proxy configuration

### ISSUE THREAD

**Issue by viscontem** [glideapps/quicktype#2436]
During external references resolution, the library fetches external schemas from the Internet. When working behind a corporate proxy, these requests are blocked.

A setting allowing the user to pass details about a HTTP(S) proxy would allow the library to work behind a corporate proxy.

**Comment by inferrinizzard** [comment]
Managing HTTP Proxies is not within the scope of quicktype, I would recommend a third-party proxy app such as Charles or Fiddler for your use case
