### ISSUE TITLE
For C# language, can you use the native JsonSerializer instead of Newtonsoft.Json?

### ISSUE THREAD

**Issue by johnib** [glideapps/quicktype#2459]
Hi,

I've been using your VSCode extension for years. It's a great one.
I'd be even greater if you would switch to using `System.Text.Json` instead of `Newtonsoft.Json`.

Thank you!

**Comment by inferrinizzard** [comment]
Hi @johnib , this is already possible on the C# Renderer if you set the `framework` option to `SystemTextJson`

**Comment by frontez** [comment]
Hi,
how to change framework option to SystemTextJson in VS Code extension?

**Comment by johnib** [comment]
> Hi [@johnib](https://github.com/johnib) , this is already possible on the C# Renderer if you set the `framework` option to `SystemTextJson`

Not sure I follow? How is that done?
