### ISSUE TITLE
[BUG]: quicktype version 23.0.161 command not found

### ISSUE THREAD

**Issue by OracleDin** [glideapps/quicktype#2597]
When installing version 23.0.161 you can't execute the quicktype command. It still works with version 23.0.158.

`npm WARN exec The following package was not found and will be installed: quicktype@23.0.161`
`sh: quicktype: command not found`

**Comment by inferrinizzard** [comment]
@OracleDin Can you try again with 23.0.162 ?

**Comment by OracleDin** [comment]
Now it works! We were working with latest in my project, now its resolved. Thanks alot :)

**Comment by inferrinizzard** [comment]
Resolved as of 23.0.162
