### ISSUE TITLE
[BUG]: factory methods are not generated for dart models

### ISSUE THREAD

**Issue by Moinuddin9777** [glideapps/quicktype#2666]
## Description

The factory method for a dart model is not being generated 
When a json response is given to the quicktype site earlier it would generate factory methods for serialization 
but there seems to be an issue that it is not generating factory methods anymore

## Current Behaviour / Output
here is a screenshot of the latest output:

![image](https://github.com/user-attachments/assets/5158384e-4e0b-4810-92e0-be059b036433)

## Expected Behaviour / Output

A factory method would look something like this:
``` 

class Product {
    int? id;
    String? name;
    List<String>? pic;
    int? price;

    Product({
        this.id,
        this.name,
        this.pic,
        this.price
    });

    factory Product.fromJson(Map<String, dynamic> json) => Product(
        id: json["id"],
        name: json["name"],
        pic: json["pic"] == null ? [] : List<String>.from(json["pic"]!.map((x) => x)),
        price: json["price"],
    );

    Map<String, dynamic> toJson() => {
        "id": id,
        "name": name,
        "pic": pic == null ? [] : List<dynamic>.from(pic!.map((x) => x)),
        "price": price,
    };
}

```

Input Format:
Any Json response from any API

Output Language:
Dart

This happens on:  
app.quicktype.io

## Input Data

```
{
  "id": 4587,
  "name": "string",
  "pic": [
    "string"
  ],
  "price": 0
}
````

**Comment by StultusRex** [comment]
Please check your options. Make sure "Types only" is un-toggled

**Comment by Moinuddin9777** [comment]
> Please check your options. Make sure "Types only" is un-toggled

Yes I did, 
Im not sure if it was any kind of bug or something
I found it strange when in the first place I didnt even get the `types only` toggle option 

After a few reloads I was able to see it but it did not render the factory method of the code
