### ISSUE TITLE
Language request: OCaml / Reason

### ISSUE THREAD

**Issue by cyrus-** [glideapps/quicktype#347]
OCaml is increasingly being used for web stuff. Two major JavaScript compilers (js_of_ocaml and Bucklescript). Reason is an alternative syntax for OCaml supported by Facebook. So it would be great to add language support for OCaml / Reason! Should be similar to the Elm support.

**Comment by dvdsgl** [comment]
How is JSON decoded in Reason? Is there some FFI where it's just casted like in TypeScript?

**Comment by dvdsgl** [comment]
Can you please provide some samples?

**Comment by cyrus-** [comment]
I'm not too experienced with JSON in Reason just yet, but I found this. https://github.com/reasonml-community/bs-json

I'll point the Reason discord to this issue in case someone has something more intelligent to say.

**Comment by schani** [comment]
We're closing new-language issues that find no contributors.

**Comment by dvdsgl** [comment]
@Cyrus we would love to have someone contribute this. If you're still interested, the best way to make this happen is to promote quicktype in the OCaml/Reason community and recruit someone willing and able to work on this. We will happily guide them.

**Comment by seanpowell** [comment]
Hey @dvdsgl - If I were to take a swing at this, where would I start? I'm currently in the throws of finessing Reason + JSON for several API libs I've developed and have a pretty good handle on what it entails.  It also helps (from a bindings perspective) to have the tight typescript integration that quick does. Love what quicktype is doing btw!

**Comment by schani** [comment]
@seanpowell That's wonderful! I recommend [Rust](https://github.com/quicktype/quicktype/blob/master/src/quicktype-core/language/Rust.ts) as a good starting point.  It's probably the most straightforward target language that implements unions and enums.

Two main approaches - pick one:

1. Copy `Rust.ts` and change it to make it produce Reason.
2. Subclass `TargetLanguage` and `ConvenienceRenderer` and implement all abstract methods the compiler complains about, taking hints from Rust and other languages, and slowly add stuff.

You'll have to add your new target language in [`All.ts`](https://github.com/quicktype/quicktype/blob/master/src/quicktype-core/language/All.ts).

We're always happy to help if you get stuck.  The quickest way to sort things out is to talk to us on [Slack](http://slack.quicktype.io).

**Comment by seanpowell** [comment]
Thanks @schani.  That definitely gets me started. I'll find you all on slack if I have any questions.
