### ISSUE TITLE
Use attributes to tidy C# enum marshalling

### ISSUE THREAD

**Issue by dvdsgl** [glideapps/quicktype#419]

**Comment by schani** [comment]
Could you give an example of what this would look like?

**Comment by dvdsgl** [comment]
```csharp
public enum Weakness {
  [Description("Fire")]
  Fire,
  [Description("Water")]
  Water,
  ...
}
```

Then we could use `Enum` and metadata methods to reflect on these attributes, rather than large switch statements and proliferating the literal strings.
