### ISSUE TITLE
What can we do for JSON-RPC?

### ISSUE THREAD

**Issue by dvdsgl** [glideapps/quicktype#474]
Apparently Ethereum nodes use JSON-RPC. Could we make these calls typesafe? Could we generate typesafe RPC client and server code?

**Comment by schani** [comment]
@carnesen Any chance you could write up your approach in a blog post?

**Comment by schani** [comment]
Oh, I was suggesting you publish it on your blog if you have one.  I guess these days Medium is the thing.  But we're happy to give you our feedback if you send us a draft, and tweet about it :-).  You can also come talk to us on [Slack](http://slack.quicktype.io).
